apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-master
  namespace: default
  labels:
        app: pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-slave
  namespace: default
  labels:
        app: pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
