apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer (If you use ClusterIP, comment here)
  ports:
  - port: 6379
    #targetPort: 6379 (If you use ClusterIP, uncomment here)
  selector:
    app: redis
    role: master
    tier: backend
