apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: default
  labels:
    app: redis-master
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  namespace: default
  labels:
    app: redis-slave
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
