kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
    storagePolicyName: "vSAN Default Storage Policy"  ## add your storege policy here if you specified
    datastoreurl: "ds:///vmfs/volumes/vsan:b7ae797645924e00-8d20f26bf7fb259f/"  ## add your Datasoreurl here
